### ISSUE TITLE
Keyboard doses not display correctly 

### ISSUE THREAD

**Issue by YesIamJeremyChen** [Telenav-Search/search-android-demo-app#23]
<img width="1170" alt="Screen Shot 2022-03-21 at 6 04 13 PM" src="https://user-images.githubusercontent.com/70997856/159240019-fbe325bb-bab8-4b20-be87-aa673da1b3ce.png">

**Comment by arambaghdasintellias** [comment]
Fixed 1,2
It is hard to fix, hope it is not critical.

**Comment by YesIamJeremyChen** [comment]
@arambaghdasintellias  I suppose you SHOULD NOT close the bug since it's not fixed totally. The priority should be confirmed with UX designer rather than made decision from dev's prospective

**Comment by arambaghdasintellias** [comment]
If test description for example  contain 10 issues, 9 fixed. To not closing it doesn't give correct picture. In that case there should be opened separate issue. I am closing to have clear picture , in case of not closing should open each issue to check description.
